In [33]:
import pandas as pd

df = pd.read_csv(r"C:\Users\rkpan\Downloads\P6-SuperStoreUS-2015.csv",encoding='latin1')
df.head()
df = df.sort_values(by='Row ID', ascending=True)

In [15]:
df.shape

(1952, 25)

In [16]:
df.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Country', 'Region',
       'State or Province', 'City', 'Postal Code', 'Order Date', 'Ship Date',
       'Profit', 'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                1952 non-null   int64
 1   Order Priority        1952 non-null   object
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64
 6   Customer Name         1952 non-null   object
 7   Ship Mode             1952 non-null   object
 8   Customer Segment      1952 non-null   object
 9   Product Category      1952 non-null   object
 10  Product Sub-Category  1952 non-null   object
 11  Product Container     1952 non-null   object
 12  Product Name          1952 non-null   object
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object
 15  Region                1952 non-null   object
 16  State or Province     1952 non-null   object
 17  City                  1952 non-null   object
 18  Postal Code           1952 non-null   int64
 19  Order Date            1952 non-null   object
 20  Ship Date             1952 non-null   object
 21  Profit                1952 non-null   float64
 22  Quantity ordered new  1952 non-null   int64
 23  Sales                 1952 non-null   float64
 24  Order ID              1952 non-null   int64
dtypes: float64(6), int64(5), object(14)
memory usage: 381.4+ KB

In [17]:
df.describe()

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Profit,Quantity ordered new,Sales,Order ID
count,1952.000000,1952.000000,1952.000000,1952.000000,1952.000000,1936.000000,1952.000000,1952.000000,1952.000000,1952.000000,1952.000000
mean,19916.479508,0.048975,109.079221,12.968151,1735.376537,0.515186,51534.769467,114.793859,12.944672,985.828832,82365.924180
std,5957.595627,0.031378,393.481301,17.414631,991.078006,0.137055,29362.828420,1141.112387,13.871565,2559.900167,19042.295798
min,64.000000,0.000000,1.140000,0.490000,3.000000,0.350000,1001.000000,-16476.838000,1.000000,2.250000,359.000000
25%,19121.000000,0.020000,6.480000,3.230000,875.000000,0.380000,28560.000000,-84.485400,5.000000,58.807500,86767.750000
50%,21164.500000,0.050000,20.990000,6.150000,1738.000000,0.525000,48765.500000,1.476450,10.000000,202.395000,88376.000000
75%,23483.250000,0.080000,100.972500,14.362500,2578.250000,0.590000,78550.000000,116.201575,16.000000,802.945000,89957.000000
max,26389.000000,0.210000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,9228.225600,167.000000,45737.330000,91586.000000

In [3]:
df.isnull().sum()
df.columns = df.columns.str.lower() \
                       .str.replace(' ', '_') \
                       .str.replace('-', '_')

NameError: name 'df' is not defined

In [21]:
df.duplicated().sum()

0

In [34]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['row_id', 'order_priority', 'discount', 'unit_price', 'shipping_cost',
       'customer_id', 'customer_name', 'ship_mode', 'customer_segment',
       'product_category', 'product_sub-category', 'product_container',
       'product_name', 'product_base_margin', 'country', 'region',
       'state_or_province', 'city', 'postal_code', 'order_date', 'ship_date',
       'profit', 'quantity_ordered_new', 'sales', 'order_id'],
      dtype='object')

In [37]:
df['order_date']=pd.to_datetime(df['order_date'])
df['ship_date']=pd.to_datetime(df['ship_date'])

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1952 entries, 297 to 972
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                1952 non-null   int64
 1   order_priority        1952 non-null   object
 2   discount              1952 non-null   float64
 3   unit_price            1952 non-null   float64
 4   shipping_cost         1952 non-null   float64
 5   customer_id           1952 non-null   int64
 6   customer_name         1952 non-null   object
 7   ship_mode             1952 non-null   object
 8   customer_segment      1952 non-null   object
 9   product_category      1952 non-null   object
 10  product_sub-category  1952 non-null   object
 11  product_container     1952 non-null   object
 12  product_name          1952 non-null   object
 13  product_base_margin   1936 non-null   float64
 14  country               1952 non-null   object
 15  region                1952 non-null   object
 16  state_or_province     1952 non-null   object
 17  city                  1952 non-null   object
 18  postal_code           1952 non-null   int64
 19  order_date            1952 non-null   datetime64[ns]
 20  ship_date             1952 non-null   datetime64[ns]
 21  profit                1952 non-null   float64
 22  quantity_ordered_new  1952 non-null   int64
 23  sales                 1952 non-null   float64
 24  order_id              1952 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(12)
memory usage: 396.5+ KB

In [39]:
df.isnull().sum()

row_id                   0
order_priority           0
discount                 0
unit_price               0
shipping_cost            0
customer_id              0
customer_name            0
ship_mode                0
customer_segment         0
product_category         0
product_sub-category     0
product_container        0
product_name             0
product_base_margin     16
country                  0
region                   0
state_or_province        0
city                     0
postal_code              0
order_date               0
ship_date                0
profit                   0
quantity_ordered_new     0
sales                    0
order_id                 0
dtype: int64

In [45]:
df['product_base_margin'] = df['product_base_margin'].fillna(df['product_base_margin'].mean())

In [46]:
df.isnull().sum()

row_id                  0
order_priority          0
discount                0
unit_price              0
shipping_cost           0
customer_id             0
customer_name           0
ship_mode               0
customer_segment        0
product_category        0
product_sub-category    0
product_container       0
product_name            0
product_base_margin     0
country                 0
region                  0
state_or_province       0
city                    0
postal_code             0
order_date              0
ship_date               0
profit                  0
quantity_ordered_new    0
sales                   0
order_id                0
dtype: int64

In [50]:
df.duplicated().sum()

0

In [54]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df['ship_date'] = pd.to_datetime(df['ship_date'], errors='coerce')

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1936 entries, 297 to 972
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                1936 non-null   int64
 1   order_priority        1936 non-null   object
 2   discount              1936 non-null   float64
 3   unit_price            1936 non-null   float64
 4   shipping_cost         1936 non-null   float64
 5   customer_id           1936 non-null   int64
 6   customer_name         1936 non-null   object
 7   ship_mode             1936 non-null   object
 8   customer_segment      1936 non-null   object
 9   product_category      1936 non-null   object
 10  product_sub-category  1936 non-null   object
 11  product_container     1936 non-null   object
 12  product_name          1936 non-null   object
 13  product_base_margin   1936 non-null   float64
 14  country               1936 non-null   object
 15  region                1936 non-null   object
 16  state_or_province     1936 non-null   object
 17  city                  1936 non-null   object
 18  postal_code           1936 non-null   int64
 19  order_date            1936 non-null   datetime64[ns]
 20  ship_date             1936 non-null   datetime64[ns]
 21  profit                1936 non-null   float64
 22  quantity_ordered_new  1936 non-null   int64
 23  sales                 1936 non-null   float64
 24  order_id              1936 non-null   int64
 25  year                  1936 non-null   int32
 26  month                 1936 non-null   int32
 27  day                   1936 non-null   int32
 28  total_amount          1936 non-null   float64
dtypes: datetime64[ns](2), float64(7), int32(3), int64(5), object(12)
memory usage: 431.1+ KB

In [56]:
df['order_date'].isnull().sum()

0

In [57]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['day'] = df['order_date'].dt.day

In [58]:
df = df.dropna(subset=['order_date'])

In [59]:
df[['order_date', 'year', 'month', 'day']].head()

     order_date  year  month  day
297  2015-06-18  2015      6   18
1768 2015-03-20  2015      3   20
1769 2015-03-20  2015      3   20
1770 2015-03-20  2015      3   20
614  2015-05-21  2015      5   21

In [60]:
df['total_amount'] = df['sales']

In [61]:
df.rename(columns={'quantity_ordered_new': 'quantity'}, inplace=True)

In [62]:
df['delivery_days'] = (df['ship_date'] - df['order_date']).dt.days

In [63]:
df['order_frequency'] = df.groupby('customer_id')['order_id'].transform('count')

In [64]:
df[['sales','total_amount','quantity','delivery_days','order_frequency']].head()

        sales  total_amount  quantity  delivery_days  order_frequency
297   6831.37       6831.37        56              1                4
1768   236.87        236.87        75              1                3
1769   370.91        370.91        53              1                3
1770  4976.92       4976.92        47              2                3
614    586.96        586.96        61              1                3

In [65]:
df.head()

,row_id,order_priority,discount,unit_price,shipping_cost,customer_id,customer_name,ship_mode,customer_segment,product_category,...,profit,quantity,sales,order_id,year,month,day,total_amount,delivery_days,order_frequency
297,64,Medium,0.08,124.49,51.94,553,Kristine Connolly,Delivery Truck,Corporate,Furniture,...,-500.380,56,6831.37,359,2015,6,18,6831.37,1,4
1768,87,Critical,0.04,3.08,0.99,3106,Alexander O'Brien,Regular Air,Home Office,Office Supplies,...,36.020,75,236.87,548,2015,3,20,236.87,1,3
1769,88,Critical,0.02,6.48,5.90,3106,Alexander O'Brien,Regular Air,Home Office,Office Supplies,...,-50.640,53,370.91,548,2015,3,20,370.91,1,3
1770,89,Critical,0.04,125.99,4.20,3106,Alexander O'Brien,Regular Air,Home Office,Technology,...,510.489,47,4976.92,548,2015,3,20,4976.92,2,3
614,106,High,0.01,9.31,3.98,1106,Maxine Collier Grady,Regular Air,Small Business,Office Supplies,...,-10.900,61,586.96,646,2015,5,21,586.96,1,3

In [66]:
df.describe()

,row_id,discount,unit_price,shipping_cost,customer_id,product_base_margin,postal_code,order_date,ship_date,profit,quantity,sales,order_id,year,month,day,total_amount,delivery_days,order_frequency
count,1936.000000,1936.000000,1936.000000,1936.000000,1936.000000,1936.000000,1936.000000,1936,1936,1936.000000,1936.000000,1936.000000,1936.000000,1936.0,1936.000000,1936.000000,1936.000000,1936.000000,1936.000000
mean,19917.548554,0.048858,108.034685,12.783280,1733.831095,0.515186,51545.004132,2015-03-29 01:14:22.809917440,2015-03-30 23:53:18.347107328,111.065806,12.965909,971.861968,82347.225207,2015.0,3.415289,15.442149,971.861968,1.943698,2.357438
min,64.000000,0.000000,1.140000,0.490000,3.000000,0.350000,1001.000000,2015-01-01 00:00:00,2015-01-02 00:00:00,-16476.838000,1.000000,2.250000,359.000000,2015.0,1.000000,1.000000,2.250000,0.000000,1.000000
25%,19121.000000,0.020000,6.480000,3.032500,874.000000,0.380000,28560.000000,2015-02-11 00:00:00,2015-02-13 00:00:00,-83.675000,5.000000,58.515000,86783.750000,2015.0,2.000000,8.000000,58.515000,1.000000,1.000000
50%,21167.500000,0.050000,20.990000,6.095000,1738.000000,0.525000,48823.000000,2015-03-27 00:00:00,2015-03-29 00:00:00,1.300200,10.000000,200.660000,88376.000000,2015.0,3.000000,15.000000,200.660000,2.000000,2.000000
75%,23499.750000,0.070000,99.230000,14.000000,2578.000000,0.590000,78550.000000,2015-05-15 00:00:00,2015-05-16 00:00:00,113.473725,16.000000,774.920000,89961.000000,2015.0,5.000000,23.000000,774.920000,2.000000,3.000000
max,26389.000000,0.210000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,2015-06-30 00:00:00,2015-07-08 00:00:00,9228.225600,167.000000,45737.330000,91586.000000,2015.0,6.000000,31.000000,45737.330000,10.000000,9.000000
std,5968.385953,0.031340,394.836173,17.289631,990.512340,0.137055,29351.770516,NaN,NaN,1136.352380,13.913943,2559.347078,19075.071929,0.0,1.722042,8.672196,2559.347078,1.712828,1.408107

In [67]:
df.to_csv("cleaned_sales.csv", index=False)

In [68]:
df.head()

,row_id,order_priority,discount,unit_price,shipping_cost,customer_id,customer_name,ship_mode,customer_segment,product_category,...,profit,quantity,sales,order_id,year,month,day,total_amount,delivery_days,order_frequency
297,64,Medium,0.08,124.49,51.94,553,Kristine Connolly,Delivery Truck,Corporate,Furniture,...,-500.380,56,6831.37,359,2015,6,18,6831.37,1,4
1768,87,Critical,0.04,3.08,0.99,3106,Alexander O'Brien,Regular Air,Home Office,Office Supplies,...,36.020,75,236.87,548,2015,3,20,236.87,1,3
1769,88,Critical,0.02,6.48,5.90,3106,Alexander O'Brien,Regular Air,Home Office,Office Supplies,...,-50.640,53,370.91,548,2015,3,20,370.91,1,3
1770,89,Critical,0.04,125.99,4.20,3106,Alexander O'Brien,Regular Air,Home Office,Technology,...,510.489,47,4976.92,548,2015,3,20,4976.92,2,3
614,106,High,0.01,9.31,3.98,1106,Maxine Collier Grady,Regular Air,Small Business,Office Supplies,...,-10.900,61,586.96,646,2015,5,21,586.96,1,3

In [69]:
df.shape

(1936, 31)

In [2]:
df.columns = df.columns.str.lower() \
                       .str.replace(' ', '_') \
                       .str.replace('-', '_')

NameError: name 'df' is not defined

In [4]:
import pandas as pd

df = pd.read_csv("cleaned_sales.csv", parse_dates=['order_date'])
df.head()

C:\Users\rkpan\AppData\Local\Temp\ipykernel_10188\3414645404.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv("cleaned_sales.csv", parse_dates=['order_date'])

,row_id,order_priority,discount,unit_price,shipping_cost,customer_id,customer_name,ship_mode,customer_segment,product_category,...,profit,quantity,sales,order_id,year,month,day,total_amount,delivery_days,order_frequency
0,64,Medium,0.08,124.49,51.94,553,Kristine Connolly,Delivery Truck,Corporate,Furniture,...,-500.380,56,6831.37,359,2015,6,18,6831.37,1,4
1,87,Critical,0.04,3.08,0.99,3106,Alexander O'Brien,Regular Air,Home Office,Office Supplies,...,36.020,75,236.87,548,2015,3,20,236.87,1,3
2,88,Critical,0.02,6.48,5.90,3106,Alexander O'Brien,Regular Air,Home Office,Office Supplies,...,-50.640,53,370.91,548,2015,3,20,370.91,1,3
3,89,Critical,0.04,125.99,4.20,3106,Alexander O'Brien,Regular Air,Home Office,Technology,...,510.489,47,4976.92,548,2015,3,20,4976.92,2,3
4,106,High,0.01,9.31,3.98,1106,Maxine Collier Grady,Regular Air,Small Business,Office Supplies,...,-10.900,61,586.96,646,2015,5,21,586.96,1,3

In [5]:
total_sales = df['sales'].sum()
print("Total Sales:", total_sales)

Total Sales: 1881524.77

In [6]:
total_orders = df['order_id'].nunique()
print("Total Orders:", total_orders)

Total Orders: 1358

In [7]:
total_customers = df['customer_id'].nunique()
print("Total Customers:", total_customers)

Total Customers: 1124

In [8]:
aov = total_sales / total_orders
print("Average Order Value:", aov)

Average Order Value: 1385.5116126656849

In [9]:
#RFM ANALYSIS
import datetime as dt

latest_date = df['order_date'].max()

rfm = df.groupby('customer_id').agg({
    'order_date': lambda x: (latest_date - x.max()).days,
    'order_id': 'count',
    'sales': 'sum'
})

In [10]:
rfm.columns = ['recency', 'frequency', 'monetary']
rfm.head()

             recency  frequency  monetary
customer_id
3                174          1     13.01
5                 17          1   6362.85
11               135          1    211.15
14                49          4   1214.93
15                33          2    413.00

In [16]:
#RFM SCORING

In [14]:
rfm['r_score'] = pd.cut(rfm['recency'], bins=4, labels=[4,3,2,1])
rfm['f_score'] = pd.cut(rfm['frequency'], bins=4, labels=[1,2,3,4])
rfm['m_score'] = pd.cut(rfm['monetary'], bins=4, labels=[1,2,3,4])

In [15]:
rfm.head()

             recency  frequency  monetary r_score f_score m_score
customer_id
3                174          1     13.01       1       1       1
5                 17          1   6362.85       4       1       1
11               135          1    211.15       2       1       1
14                49          4   1214.93       3       2       1
15                33          2    413.00       4       1       1

In [17]:
#CUSTOMER SEGMENTS
rfm['segment'] = rfm['r_score'].astype(str) + rfm['f_score'].astype(str)
rfm.head()

             recency  frequency  monetary r_score f_score m_score segment
customer_id
3                174          1     13.01       1       1       1      11
5                 17          1   6362.85       4       1       1      41
11               135          1    211.15       2       1       1      21
14                49          4   1214.93       3       2       1      32
15                33          2    413.00       4       1       1      41

In [18]:
#BASIC INSIGHTS
rfm.sort_values(by='monetary', ascending=False).head()

             recency  frequency  monetary r_score f_score m_score segment
customer_id
553               12          4  50475.31       4       2       4      42
1733               2          3  48295.12       4       1       4      41
491               10          4  32194.12       4       2       3      42
2571              66          2  29916.01       3       1       3      31
2670              32          2  28779.13       4       1       3      41

In [19]:
rfm['segment'].value_counts()

segment
41    302
31    263
11    245
21    236
42     31
32     20
22     13
12      5
43      4
44      2
23      2
33      1
Name: count, dtype: int64